name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions default runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kill existing bot.py process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: pkill -f bot.py

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}  # Raspberry Pi IP address or hostname
          username: ${{ secrets.PI_USERNAME }}  # Raspberry Pi SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for authentication
          password: "yrrebpsaR"
          source: "."  # Source directory or files to copy
          target: "~/KaMS-Club-Bot"  # Target directory on Raspberry Pi

      - name: Run deployment script on Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/KaMS-Club-Bot
            python3 bot.py
