# CI/CD Workflow to Connect to Raspberry Pi in Home network.

name: Raspberry Pi Connect

on:
  push:
    branches: [main]

jobs:
  test-connectivity:
    name: Test connectivity
    runs-on: ubuntu-latest
    steps:
      - name: Test access to host (remote ssh commands)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            hostname -I | awk '{print $1}'
            curl ifconfig.me
