name: Update Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2
        architecture: arm64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Transfer code to Raspberry Pi
      run: |
        ssh pi@raspberry.local 'mkdir -p ~/app'
        scp -r * pi@raspberry.local:~/app

    - name: Restart bot.py on Raspberry Pi
      run: |
        ssh pi@raspberry.local 'pkill -f bot.py'
        ssh pi@raspberry.local 'cd ~/app && python bot.py &'

    # Optionally, add more steps for testing, notifications, etc.
