name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust as per your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions default runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}  # Raspberry Pi IP address or hostname
          username: ${{ secrets.PI_USERNAME }}  # Raspberry Pi SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for authentication
          source: "."  # Source directory or files to copy
          target: "/path/to/destination/folder"  # Target directory on Raspberry Pi

