name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RASPBERRY_PI_HOSTNAME: raspberry.local  # Replace with your Raspberry Pi's hostname

    steps:
      - name: Set up SSH keys and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $RASPBERRY_PI_HOSTNAME >> ~/.ssh/known_hosts

      - name: Create directory on Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_HOSTNAME 'mkdir -p ~/app' || { echo "Failed to create directory ~/app on Raspberry Pi"; exit 1; }

      - name: Copy files to Raspberry Pi
        run: |
          scp -o StrictHostKeyChecking=no -r * pi@$RASPBERRY_PI_HOSTNAME:~/app || { echo "Failed to copy files to Raspberry Pi"; exit 1; }

      - name: Execute deployment script on Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_HOSTNAME 'cd ~/app && ./deploy_script.sh' || { echo "Failed to execute deploy_script.sh on Raspberry Pi"; exit 1; }

      - name: Cleanup SSH keys
        run: |
          rm -rf ~/.ssh

      - name: Finish Deployment
        run: |
          echo "Deployment to Raspberry Pi completed successfully."
