name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions default runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Kill existing bot.py process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pkill -f "[b]ot.py" || [ $? -eq 1 ]
            TIMEOUT=60
            while pgrep -f "[b]ot.py"; do
              if [ $TIMEOUT -le 0 ]; then
                echo "Error: bot.py did not stop within 60 seconds."
                exit 1
              fi
              sleep 1
              TIMEOUT=$((TIMEOUT-1))
            done

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "src/"
          target: "~/KaMS-Club-Bot/src/"
          rm: true
          strip_components: 1

      - name: Check if upgrade script is non-empty
        id: check_script
        run: |
          if [ -s upgrade_script.sh ]; then
            echo "SCRIPT_NON_EMPTY=true" >> $GITHUB_ENV
          else
            echo "SCRIPT_NON_EMPTY=false" >> $GITHUB_ENV
          fi

      - name: Copy over upgrade script
        if: env.SCRIPT_NON_EMPTY == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "upgrade_script.sh"
          target: "~/KaMS-Club-Bot/"
          overwrite: true

      - name: Run & delete upgrade script
        if: env.SCRIPT_NON_EMPTY == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/KaMS-Club-Bot
            chmod +x upgrade_script.sh
            ./upgrade_script.sh
            rm ~/KaMS-Club-Bot/upgrade_script.sh

      - name: Install dependencies on Raspberry Pi and run bot.py
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/KaMS-Club-Bot
            if [ ! -d "venv" ]; then
              python3.12 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r <(curl -sL "https://raw.githubusercontent.com/${{ github.repository }}/main/requirements.txt")
            export DISCORD_BOT_TOKEN="${{ secrets.DISCORD_BOT_TOKEN }}"
            nohup python3.12 src/bot.py >> ./bot.log 2>&1 &
