name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions default runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          path: "src"
          sha: ${{ github.event.before }}
          separator: ","

      - name: Kill existing bot.py process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: pkill -f "[b]ot.py" || [ $? -eq 1 ]

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: "~/KaMS-Club-Bot/src/"
          rm: true
          strip_components: 1

      - name: Install dependencies on Raspberry Pi and run bot.py
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/KaMS-Club-Bot
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r <(curl -sL "https://raw.githubusercontent.com/${{ github.repository }}/main/requirements.txt")
            export DISCORD_BOT_TOKEN="${{ secrets.DISCORD_BOT_TOKEN }}"
            nohup python3 ./src/bot.py > ./bot.log 2>&1 &
